export const SHOW_MOBILE_SIDEBAR = 'SHOW_MOBILE_SIDEBAR';
export const HIDE_MOBILE_SIDEBAR = 'HIDE_MOBILE_SIDEBAR';
export const SITE_CURRENCY_AED = 'SITE_CURRENCY_AED';
export const SITE_CURRENCY_USD = 'SITE_CURRENCY_USD';

export const IS_SHIPPING = 'IS_SHIPPING';
export const NOT_SHIPPING = 'NOT_SHIPPING';
