export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const CUSTOMER_USER_ID = 'CUSTOMER_USER_ID';

export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';

export const CLEAR_ERROR = 'CLEAR_ERROR';
